#include "gbcpu.h"


// TODO move to cpuop.c after impl
cpuinst inst[256] = {
	/* 0x00 */	{"",		"", 	NULL,		0,		0},
	/* 0x01 */	{"",		"", 	NULL,		0,		0},
	/* 0x02 */	{"LD (BC),A",	"load reg a into ind bc", 	op_ld_ind_bc_reg_a,		0,		8},
	/* 0x03 */	{"",		"", 	NULL,		0,		0},
	/* 0x04 */	{"",		"", 	NULL,		0,		0},
	/* 0x05 */	{"",		"", 	NULL,		0,		0},
	/* 0x06 */	{"LD B,n",		"load imm n8 into reg b", 	op_ld_reg_b_imm_n,		1,		8},
	/* 0x07 */	{"",		"", 	NULL,		0,		0},
	/* 0x08 */	{"",		"", 	NULL,		0,		0},
	/* 0x09 */	{"",		"", 	NULL,		0,		0},
	/* 0x0A */	{"LD A,(BC)",	"load ind bc into reg a", 	op_ld_reg_a_ind_bc,		0,		8},
	/* 0x0B */	{"",		"", 	NULL,		0,		0},
	/* 0x0C */	{"",		"", 	NULL,		0,		0},
	/* 0x0D */	{"",		"", 	NULL,		0,		0},
	/* 0x0E */	{"LD C,n",		"load imm n8 into reg c", 	op_ld_reg_c_imm_n,		1,		8},
	/* 0x0F */	{"",		"", 	NULL,		0,		0},
	/* 0x10 */	{"",		"", 	NULL,		0,		0},
	/* 0x11 */	{"",		"", 	NULL,		0,		0},
	/* 0x12 */	{"LD (DE),A",	"load reg a into ind de", 	op_ld_ind_de_reg_a,		0,		8},
	/* 0x13 */	{"",		"", 	NULL,		0,		0},
	/* 0x14 */	{"",		"", 	NULL,		0,		0},
	/* 0x15 */	{"",		"", 	NULL,		0,		0},
	/* 0x16 */	{"LD D,n",		"load imm n8 into reg d", 	op_ld_reg_d_imm_n,		1,		8},
	/* 0x17 */	{"",		"", 	NULL,		0,		0},
	/* 0x18 */	{"",		"", 	NULL,		0,		0},
	/* 0x19 */	{"",		"", 	NULL,		0,		0},
	/* 0x1A */	{"LD A,(DE)",	"load ind de into reg a", 	op_ld_reg_a_ind_de,		0,		8},
	/* 0x1B */	{"",		"", 	NULL,		0,		0},
	/* 0x1C */	{"",		"", 	NULL,		0,		0},
	/* 0x1D */	{"",		"", 	NULL,		0,		0},
	/* 0x1E */	{"LD E,n",		"load imm n8 into reg e", 	op_ld_reg_e_imm_n,		1,		8},
	/* 0x1F */	{"",		"", 	NULL,		0,		0},
	/* 0x20 */	{"",		"", 	NULL,		0,		0},
	/* 0x21 */	{"",		"", 	NULL,		0,		0},
	/* 0x22 */	{"",		"", 	NULL,		0,		0},
	/* 0x23 */	{"",		"", 	NULL,		0,		0},
	/* 0x24 */	{"",		"", 	NULL,		0,		0},
	/* 0x25 */	{"",		"", 	NULL,		0,		0},
	/* 0x26 */	{"LD H,n",		"load imm n8 into reg h", 	op_ld_reg_h_imm_n,		1,		8},
	/* 0x27 */	{"",		"", 	NULL,		0,		0},
	/* 0x28 */	{"",		"", 	NULL,		0,		0},
	/* 0x29 */	{"",		"", 	NULL,		0,		0},
	/* 0x2A */	{"",		"", 	NULL,		0,		0},
	/* 0x2B */	{"",		"", 	NULL,		0,		0},
	/* 0x2C */	{"",		"", 	NULL,		0,		0},
	/* 0x2D */	{"",		"", 	NULL,		0,		0},
	/* 0x2E */	{"LD L,n",		"load imm n8 into reg l", 	op_ld_reg_l_imm_n,		1,		8},
	/* 0x2F */	{"",		"", 	NULL,		0,		0},
	/* 0x30 */	{"",		"", 	NULL,		0,		0},
	/* 0x31 */	{"",		"", 	NULL,		0,		0},
	/* 0x32 */	{"",		"", 	NULL,		0,		0},
	/* 0x33 */	{"",		"", 	NULL,		0,		0},
	/* 0x34 */	{"",		"", 	NULL,		0,		0},
	/* 0x35 */	{"",		"", 	NULL,		0,		0},
	/* 0x36 */	{"LD (HL),n",	"load imm n8 into ind hl", 	op_ld_ind_hl_imm_n,		1,		12},
	/* 0x37 */	{"",		"", 	NULL,		0,		0},
	/* 0x38 */	{"",		"", 	NULL,		0,		0},
	/* 0x39 */	{"",		"", 	NULL,		0,		0},
	/* 0x3A */	{"",		"", 	NULL,		0,		0},
	/* 0x3B */	{"",		"", 	NULL,		0,		0},
	/* 0x3C */	{"",		"", 	NULL,		0,		0},
	/* 0x3D */	{"",		"", 	NULL,		0,		0},
	/* 0x3E */	{"LD A,#",		"load imm n8 into reg a", 	op_ld_reg_a_imm_n,		1,		8},
	/* 0x3F */	{"",		"", 	NULL,		0,		0},
	/* 0x40 */	{"LD B,B",		"load reg b into reg b", 	op_ld_reg_b_reg_b,		0,		4},
	/* 0x41 */	{"LD B,C",		"load reg c into reg b", 	op_ld_reg_b_reg_c,		0,		4},
	/* 0x42 */	{"LD B,D",		"load reg d into reg b", 	op_ld_reg_b_reg_d,		0,		4},
	/* 0x43 */	{"LD B,E",		"load reg e into reg b", 	op_ld_reg_b_reg_e,		0,		4},
	/* 0x44 */	{"LD B,H",		"load reg h into reg b", 	op_ld_reg_b_reg_h,		0,		4},
	/* 0x45 */	{"LD B,L",		"load reg l into reg b", 	op_ld_reg_b_reg_l,		0,		4},
	/* 0x46 */	{"LD B,(HL)",	"load ind hl into reg b", 	op_ld_reg_b_ind_hl,		0,		8},
	/* 0x47 */	{"LD B,A",		"load reg a into reg b", 	op_ld_reg_b_reg_a,		0,		4},
	/* 0x48 */	{"LD C,B",		"load reg b into reg c", 	op_ld_reg_c_reg_b,		0,		4},
	/* 0x49 */	{"LD C,C",		"load reg c into reg c", 	op_ld_reg_c_reg_c,		0,		4},
	/* 0x4A */	{"LD C,D",		"load reg d into reg c", 	op_ld_reg_c_reg_d,		0,		4},
	/* 0x4B */	{"LD C,E",		"load reg e into reg c", 	op_ld_reg_c_reg_e,		0,		4},
	/* 0x4C */	{"LD C,H",		"load reg h into reg c", 	op_ld_reg_c_reg_h,		0,		4},
	/* 0x4D */	{"LD C,L",		"load reg l into reg c", 	op_ld_reg_c_reg_l,		0,		4},
	/* 0x4E */	{"LD C,(HL)",	"load ind hl into reg c", 	op_ld_reg_c_ind_hl,		0,		8},
	/* 0x4F */	{"LD C,A",		"load reg a into reg c", 	op_ld_reg_c_reg_a,		0,		4},
	/* 0x50 */	{"LD D,B",		"load reg b into reg d", 	op_ld_reg_d_reg_b,		0,		4},
	/* 0x51 */	{"LD D,C",		"load reg c into reg d", 	op_ld_reg_d_reg_c,		0,		4},
	/* 0x52 */	{"LD D,D",		"load reg d into reg d", 	op_ld_reg_d_reg_d,		0,		4},
	/* 0x53 */	{"LD D,E",		"load reg e into reg d", 	op_ld_reg_d_reg_e,		0,		4},
	/* 0x54 */	{"LD D,H",		"load reg h into reg d", 	op_ld_reg_d_reg_h,		0,		4},
	/* 0x55 */	{"LD D,L",		"load reg l into reg d", 	op_ld_reg_d_reg_l,		0,		4},
	/* 0x56 */	{"LD D,(HL)",	"load ind hl into reg d", 	op_ld_reg_d_ind_hl,		0,		8},
	/* 0x57 */	{"LD D,A",		"load reg a into reg d", 	op_ld_reg_d_reg_a,		0,		4},
	/* 0x58 */	{"LD E,B",		"load reg b into reg e", 	op_ld_reg_e_reg_b,		0,		4},
	/* 0x59 */	{"LD E,C",		"load reg c into reg e", 	op_ld_reg_e_reg_c,		0,		4},
	/* 0x5A */	{"LD E,D",		"load reg d into reg e", 	op_ld_reg_e_reg_d,		0,		4},
	/* 0x5B */	{"LD E,E",		"load reg e into reg e", 	op_ld_reg_e_reg_e,		0,		4},
	/* 0x5C */	{"LD E,H",		"load reg h into reg e", 	op_ld_reg_e_reg_h,		0,		4},
	/* 0x5D */	{"LD E,L",		"load reg l into reg e", 	op_ld_reg_e_reg_l,		0,		4},
	/* 0x5E */	{"LD E,(HL)",	"load ind hl into reg e", 	op_ld_reg_e_ind_hl,		0,		8},
	/* 0x5F */	{"LD E,A",		"load reg a into reg e", 	op_ld_reg_e_reg_a,		0,		4},
	/* 0x60 */	{"LD H,B",		"load reg b into reg h", 	op_ld_reg_h_reg_b,		0,		4},
	/* 0x61 */	{"LD H,C",		"load reg c into reg h", 	op_ld_reg_h_reg_c,		0,		4},
	/* 0x62 */	{"LD H,D",		"load reg d into reg h", 	op_ld_reg_h_reg_d,		0,		4},
	/* 0x63 */	{"LD H,E",		"load reg e into reg h", 	op_ld_reg_h_reg_e,		0,		4},
	/* 0x64 */	{"LD H,H",		"load reg h into reg h", 	op_ld_reg_h_reg_h,		0,		4},
	/* 0x65 */	{"LD H,L",		"load reg l into reg h", 	op_ld_reg_h_reg_l,		0,		4},
	/* 0x66 */	{"LD H,(HL)",	"load ind hl into reg h", 	op_ld_reg_h_ind_hl,		0,		8},
	/* 0x67 */	{"LD H,A",		"load reg a into reg h", 	op_ld_reg_h_reg_a,		0,		4},
	/* 0x68 */	{"LD L,B",		"load reg b into reg l", 	op_ld_reg_l_reg_b,		0,		4},
	/* 0x69 */	{"LD L,C",		"load reg c into reg l", 	op_ld_reg_l_reg_c,		0,		4},
	/* 0x6A */	{"LD L,D",		"load reg d into reg l", 	op_ld_reg_l_reg_d,		0,		4},
	/* 0x6B */	{"LD L,E",		"load reg e into reg l", 	op_ld_reg_l_reg_e,		0,		4},
	/* 0x6C */	{"LD L,H",		"load reg h into reg l", 	op_ld_reg_l_reg_h,		0,		4},
	/* 0x6D */	{"LD L,L",		"load reg l into reg l", 	op_ld_reg_l_reg_l,		0,		4},
	/* 0x6E */	{"LD L,(HL)",	"load ind hl into reg l", 	op_ld_reg_l_ind_hl,		0,		8},
	/* 0x6F */	{"LD L,A",		"load reg a into reg l", 	op_ld_reg_l_reg_a,		0,		4},
	/* 0x70 */	{"LD (HL),B",	"load reg b into ind hl", 	op_ld_ind_hl_reg_b,		0,		8},
	/* 0x71 */	{"LD (HL),C",	"load reg c into ind hl", 	op_ld_ind_hl_reg_c,		0,		8},
	/* 0x72 */	{"LD (HL),D",	"load reg d into ind hl", 	op_ld_ind_hl_reg_d,		0,		8},
	/* 0x73 */	{"LD (HL),E",	"load reg e into ind hl", 	op_ld_ind_hl_reg_e,		0,		8},
	/* 0x74 */	{"LD (HL),H",	"load reg h into ind hl", 	op_ld_ind_hl_reg_h,		0,		8},
	/* 0x75 */	{"LD (HL),L",	"load reg l into ind hl", 	op_ld_ind_hl_reg_l,		0,		8},
	/* 0x76 */	{"",		"", 	NULL,		0,		0},
	/* 0x77 */	{"LD (HL),A",	"load reg a into ind hl", 	op_ld_ind_hl_reg_a,		0,		8},
	/* 0x78 */	{"LD A,B",		"load reg b into reg a", 	op_ld_reg_a_reg_b,		0,		4},
	/* 0x79 */	{"LD A,C",		"load reg c into reg a", 	op_ld_reg_a_reg_c,		0,		4},
	/* 0x7A */	{"LD A,D",		"load reg d into reg a", 	op_ld_reg_a_reg_d,		0,		4},
	/* 0x7B */	{"LD A,E",		"load reg e into reg a", 	op_ld_reg_a_reg_e,		0,		4},
	/* 0x7C */	{"LD A,H",		"load reg h into reg a", 	op_ld_reg_a_reg_h,		0,		4},
	/* 0x7D */	{"LD A,L",		"load reg l into reg a", 	op_ld_reg_a_reg_l,		0,		4},
	/* 0x7E */	{"LD A,(HL)",	"load ind hl into reg a", 	op_ld_reg_a_ind_hl,		0,		8},
	/* 0x7F */	{"LD A,A",		"load reg a into reg a", 	op_ld_reg_a_reg_a,		0,		4},
	/* 0x80 */	{"",		"", 	NULL,		0,		0},
	/* 0x81 */	{"",		"", 	NULL,		0,		0},
	/* 0x82 */	{"",		"", 	NULL,		0,		0},
	/* 0x83 */	{"",		"", 	NULL,		0,		0},
	/* 0x84 */	{"",		"", 	NULL,		0,		0},
	/* 0x85 */	{"",		"", 	NULL,		0,		0},
	/* 0x86 */	{"",		"", 	NULL,		0,		0},
	/* 0x87 */	{"",		"", 	NULL,		0,		0},
	/* 0x88 */	{"",		"", 	NULL,		0,		0},
	/* 0x89 */	{"",		"", 	NULL,		0,		0},
	/* 0x8A */	{"",		"", 	NULL,		0,		0},
	/* 0x8B */	{"",		"", 	NULL,		0,		0},
	/* 0x8C */	{"",		"", 	NULL,		0,		0},
	/* 0x8D */	{"",		"", 	NULL,		0,		0},
	/* 0x8E */	{"",		"", 	NULL,		0,		0},
	/* 0x8F */	{"",		"", 	NULL,		0,		0},
	/* 0x90 */	{"",		"", 	NULL,		0,		0},
	/* 0x91 */	{"",		"", 	NULL,		0,		0},
	/* 0x92 */	{"",		"", 	NULL,		0,		0},
	/* 0x93 */	{"",		"", 	NULL,		0,		0},
	/* 0x94 */	{"",		"", 	NULL,		0,		0},
	/* 0x95 */	{"",		"", 	NULL,		0,		0},
	/* 0x96 */	{"",		"", 	NULL,		0,		0},
	/* 0x97 */	{"",		"", 	NULL,		0,		0},
	/* 0x98 */	{"",		"", 	NULL,		0,		0},
	/* 0x99 */	{"",		"", 	NULL,		0,		0},
	/* 0x9A */	{"",		"", 	NULL,		0,		0},
	/* 0x9B */	{"",		"", 	NULL,		0,		0},
	/* 0x9C */	{"",		"", 	NULL,		0,		0},
	/* 0x9D */	{"",		"", 	NULL,		0,		0},
	/* 0x9E */	{"",		"", 	NULL,		0,		0},
	/* 0x9F */	{"",		"", 	NULL,		0,		0},
	/* 0xA0 */	{"",		"", 	NULL,		0,		0},
	/* 0xA1 */	{"",		"", 	NULL,		0,		0},
	/* 0xA2 */	{"",		"", 	NULL,		0,		0},
	/* 0xA3 */	{"",		"", 	NULL,		0,		0},
	/* 0xA4 */	{"",		"", 	NULL,		0,		0},
	/* 0xA5 */	{"",		"", 	NULL,		0,		0},
	/* 0xA6 */	{"",		"", 	NULL,		0,		0},
	/* 0xA7 */	{"",		"", 	NULL,		0,		0},
	/* 0xA8 */	{"",		"", 	NULL,		0,		0},
	/* 0xA9 */	{"",		"", 	NULL,		0,		0},
	/* 0xAA */	{"",		"", 	NULL,		0,		0},
	/* 0xAB */	{"",		"", 	NULL,		0,		0},
	/* 0xAC */	{"",		"", 	NULL,		0,		0},
	/* 0xAD */	{"",		"", 	NULL,		0,		0},
	/* 0xAE */	{"",		"", 	NULL,		0,		0},
	/* 0xAF */	{"",		"", 	NULL,		0,		0},
	/* 0xB0 */	{"",		"", 	NULL,		0,		0},
	/* 0xB1 */	{"",		"", 	NULL,		0,		0},
	/* 0xB2 */	{"",		"", 	NULL,		0,		0},
	/* 0xB3 */	{"",		"", 	NULL,		0,		0},
	/* 0xB4 */	{"",		"", 	NULL,		0,		0},
	/* 0xB5 */	{"",		"", 	NULL,		0,		0},
	/* 0xB6 */	{"",		"", 	NULL,		0,		0},
	/* 0xB7 */	{"",		"", 	NULL,		0,		0},
	/* 0xB8 */	{"",		"", 	NULL,		0,		0},
	/* 0xB9 */	{"",		"", 	NULL,		0,		0},
	/* 0xBA */	{"",		"", 	NULL,		0,		0},
	/* 0xBB */	{"",		"", 	NULL,		0,		0},
	/* 0xBC */	{"",		"", 	NULL,		0,		0},
	/* 0xBD */	{"",		"", 	NULL,		0,		0},
	/* 0xBE */	{"",		"", 	NULL,		0,		0},
	/* 0xBF */	{"",		"", 	NULL,		0,		0},
	/* 0xC0 */	{"",		"", 	NULL,		0,		0},
	/* 0xC1 */	{"",		"", 	NULL,		0,		0},
	/* 0xC2 */	{"",		"", 	NULL,		0,		0},
	/* 0xC3 */	{"",		"", 	NULL,		0,		0},
	/* 0xC4 */	{"",		"", 	NULL,		0,		0},
	/* 0xC5 */	{"",		"", 	NULL,		0,		0},
	/* 0xC6 */	{"",		"", 	NULL,		0,		0},
	/* 0xC7 */	{"",		"", 	NULL,		0,		0},
	/* 0xC8 */	{"",		"", 	NULL,		0,		0},
	/* 0xC9 */	{"",		"", 	NULL,		0,		0},
	/* 0xCA */	{"",		"", 	NULL,		0,		0},
	/* 0xCB */	{"",		"", 	NULL,		0,		0},
	/* 0xCC */	{"",		"", 	NULL,		0,		0},
	/* 0xCD */	{"",		"", 	NULL,		0,		0},
	/* 0xCE */	{"",		"", 	NULL,		0,		0},
	/* 0xCF */	{"",		"", 	NULL,		0,		0},
	/* 0xD0 */	{"",		"", 	NULL,		0,		0},
	/* 0xD1 */	{"",		"", 	NULL,		0,		0},
	/* 0xD2 */	{"",		"", 	NULL,		0,		0},
	/* 0xD3 */	{"",		"", 	NULL,		0,		0},
	/* 0xD4 */	{"",		"", 	NULL,		0,		0},
	/* 0xD5 */	{"",		"", 	NULL,		0,		0},
	/* 0xD6 */	{"",		"", 	NULL,		0,		0},
	/* 0xD7 */	{"",		"", 	NULL,		0,		0},
	/* 0xD8 */	{"",		"", 	NULL,		0,		0},
	/* 0xD9 */	{"",		"", 	NULL,		0,		0},
	/* 0xDA */	{"",		"", 	NULL,		0,		0},
	/* 0xDB */	{"",		"", 	NULL,		0,		0},
	/* 0xDC */	{"",		"", 	NULL,		0,		0},
	/* 0xDD */	{"",		"", 	NULL,		0,		0},
	/* 0xDE */	{"",		"", 	NULL,		0,		0},
	/* 0xDF */	{"",		"", 	NULL,		0,		0},
	/* 0xE0 */	{"",		"", 	NULL,		0,		0},
	/* 0xE1 */	{"",		"", 	NULL,		0,		0},
	/* 0xE2 */	{"",		"", 	NULL,		0,		0},
	/* 0xE3 */	{"",		"", 	NULL,		0,		0},
	/* 0xE4 */	{"",		"", 	NULL,		0,		0},
	/* 0xE5 */	{"",		"", 	NULL,		0,		0},
	/* 0xE6 */	{"",		"", 	NULL,		0,		0},
	/* 0xE7 */	{"",		"", 	NULL,		0,		0},
	/* 0xE8 */	{"",		"", 	NULL,		0,		0},
	/* 0xE9 */	{"",		"", 	NULL,		0,		0},
	/* 0xEA */	{"LD (nn),A",	"load reg a into ind nn", 	op_ld_ind_nn_reg_a,		2,		16},
	/* 0xEB */	{"",		"", 	NULL,		0,		0},
	/* 0xEC */	{"",		"", 	NULL,		0,		0},
	/* 0xED */	{"",		"", 	NULL,		0,		0},
	/* 0xEE */	{"",		"", 	NULL,		0,		0},
	/* 0xEF */	{"",		"", 	NULL,		0,		0},
	/* 0xF0 */	{"",		"", 	NULL,		0,		0},
	/* 0xF1 */	{"",		"", 	NULL,		0,		0},
	/* 0xF2 */	{"",		"", 	NULL,		0,		0},
	/* 0xF3 */	{"",		"", 	NULL,		0,		0},
	/* 0xF4 */	{"",		"", 	NULL,		0,		0},
	/* 0xF5 */	{"",		"", 	NULL,		0,		0},
	/* 0xF6 */	{"",		"", 	NULL,		0,		0},
	/* 0xF7 */	{"",		"", 	NULL,		0,		0},
	/* 0xF8 */	{"",		"", 	NULL,		0,		0},
	/* 0xF9 */	{"",		"", 	NULL,		0,		0},
	/* 0xFA */	{"LD A,(nn)",	"load ind nn into reg a", 	op_ld_reg_a_ind_nn,		2,		16},
	/* 0xFB */	{"",		"", 	NULL,		0,		0},
	/* 0xFC */	{"",		"", 	NULL,		0,		0},
	/* 0xFD */	{"",		"", 	NULL,		0,		0},
	/* 0xFE */	{"",		"", 	NULL,		0,		0},
	/* 0xFF */	{"",		"", 	NULL,		0,		0},


};

void gb_init() {

}
void gb_reset() {
	reg.pc = 0x100;
}
void gb_load() {

}

void gb_step() {

}




