#include "gbcpu.h"


// TODO move to cpuop.c after impl
cpuinst inst[256] = {
    /* 00 */	{"",		"", 	NULL,		0,		0},
    /* 01 */	{"LD BC,nn",	"load imm nn into bc",  	ld_reg_bc_imm_nn,		2,		12},
    /* 02 */	{"LD (BC),A",	"load reg a into ind bc", 	op_ld_ind_bc_reg_a,		0,		8},
    /* 03 */	{"INC BC",		"inc reg bc", 	            op_inc_reg_bc,		    0,		8},
    /* 04 */	{"INC B",		"inc reg b", 	            op_inc_reg_b,		    0,		4},
    /* 05 */	{"DEC B",		"dec reg b", 	            op_dec_reg_b,		    0,		4},
    /* 06 */	{"LD B,n",		"load imm n into reg b", 	op_ld_reg_b_imm_n,		1,		8},
    /* 07 */	{"",		"", 	NULL,		0,		0},
    /* 08 */	{"LD (nn),SP",	"load imm nn into sp", 	    op_ld_imm_nn_sp,		2,		20},
    /* 09 */	{"ADD HL,BC",	"add reg bc to reg hl", 	op_add_reg_hl_reg_bc,	0,		8},
    /* 0A */	{"LD A,(BC)",	"load ind bc into reg a", 	op_ld_reg_a_ind_bc,		0,		8},
    /* 0B */	{"DEC BC",		"dec reg bc", 	            op_dec_reg_bc,		    0,		8},
    /* 0C */	{"INC C",		"inc reg c", 	            op_inc_reg_c,		    0,		4},
    /* 0D */	{"DEC C",		"dec reg c", 	            op_dec_reg_c,		    0,		4},
    /* 0E */	{"LD C,n",		"load imm n into reg c", 	op_ld_reg_c_imm_n,		1,		8},
    /* 0F */	{"",		"", 	NULL,		0,		0},
    /* 10 */	{"",		"", 	NULL,		0,		0},
    /* 11 */	{"LD DE,nn",	"load imm nn into reg de", 	ld_reg_de_imm_nn,		2,		12},
    /* 12 */	{"LD (DE),A",	"load reg a into ind de", 	op_ld_ind_de_reg_a,		0,		8},
    /* 13 */	{"INC DE",		"inc reg de", 	            op_inc_reg_de,		    0,		8},
    /* 14 */	{"INC D",		"inc reg d", 	            op_inc_reg_d,		    0,		4},
    /* 15 */	{"DEC D",		"dec reg d", 	            op_dec_reg_d,		    0,		4},
    /* 16 */	{"LD D,n",		"load imm n into reg d", 	op_ld_reg_d_imm_n,		1,		8},
    /* 17 */	{"",		"", 	NULL,		0,		0},
    /* 18 */	{"",		"", 	NULL,		0,		0},
    /* 19 */	{"ADD HL,DE",	"add reg de to reg hl", 	op_add_reg_hl_reg_de,	0,		8},
    /* 1A */	{"LD A,(DE)",	"load ind de into reg a", 	op_ld_reg_a_ind_de,		0,		8},
    /* 1B */	{"DEC DE",		"dec reg de", 	            op_dec_reg_de,		    0,		8},
    /* 1C */	{"INC E",		"inc reg e", 	            op_inc_reg_e,		    0,		4},
    /* 1D */	{"DEC E",		"dec reg e", 	            op_dec_reg_e,		    0,		4},
    /* 1E */	{"LD E,n",		"load imm n into reg e", 	op_ld_reg_e_imm_n,		1,		8},
    /* 1F */	{"",		"", 	NULL,		0,		0},
    /* 20 */	{"",		"", 	NULL,		0,		0},
    /* 21 */	{"LD HL,nn",	"load imm nn into reg hl", 	ld_reg_hl_imm_nn,		2,		12},
    /* 22 */	{"LDI (HL),A",	"ld reg a to ind hl, hl+", 	op_ldi_ind_hl_reg_a,	0,		8},
    /* 23 */	{"INC HL",		"inc reg hl", 	            op_inc_reg_hl,		    0,		8},
    /* 24 */	{"INC H",		"inc reg h", 	            op_inc_reg_h,		    0,		4},
    /* 25 */	{"DEC H",		"dec reg h", 	            op_dec_reg_h,		    0,		4},
    /* 26 */	{"LD H,n",		"load imm n into reg h", 	op_ld_reg_h_imm_n,		1,		8},
    /* 27 */	{"",		"", 	NULL,		0,		0},
    /* 28 */	{"",		"", 	NULL,		0,		0},
    /* 29 */	{"ADD HL,HL",	"add reg hl to reg hl", 	op_add_reg_hl_reg_hl,	0,		8},
    /* 2A */	{"LDI A,(HL)",	"ld ind hl to reg a, hl+", 	op_ldi_reg_a_ind_hl,	0,		8},
    /* 2B */	{"DEC HL",		"dec reg hl", 	            op_dec_reg_hl,		    0,		8},
    /* 2C */	{"INC L",		"inc reg l", 	            op_inc_reg_l,		    0,		4},
    /* 2D */	{"DEC L",		"dec reg l", 	            op_dec_reg_l,		    0,		4},
    /* 2E */	{"LD L,n",		"load imm n into reg l", 	op_ld_reg_l_imm_n,		1,		8},
    /* 2F */	{"",		"", 	NULL,		0,		0},
    /* 30 */	{"",		"", 	NULL,		0,		0},
    /* 31 */	{"LD SP,nn",	"load imm nn into reg sp", 	ld_reg_sp_imm_nn,		2,		12},
    /* 32 */	{"LDD (HL),A",	"ld reg a to ind hl, hl-", 	op_ldd_ind_hl_reg_a,	0,		8},
    /* 33 */	{"INC SP",		"inc reg sp", 	            op_inc_reg_sp,		    0,		8},
    /* 34 */	{"INC (HL)",	"inc ind hl", 	            op_inc_ind_hl,		    0,		12},
    /* 35 */	{"DEC (HL)",	"dec ind hl", 	            op_dec_ind_hl,		    0,		12},
    /* 36 */	{"LD (HL),n",	"load imm n into ind hl",   op_ld_ind_hl_imm_n,		1,		12},
    /* 37 */	{"",		"", 	NULL,		0,		0},
    /* 38 */	{"",		"", 	NULL,		0,		0},
    /* 39 */	{"ADD HL,SP",	"add reg sp to reg hl", 	op_add_reg_hl_reg_sp,	0,		8},
    /* 3A */	{"LDD A,(HL)",	"ld ind hl to reg a, hl-",  op_ldd_reg_a_ind_hl,	0,		8},
    /* 3B */	{"DEC SP",		"dec reg sp", 	            op_dec_reg_sp,		    0,		8},
    /* 3C */	{"INC A",		"inc reg a", 	            op_inc_reg_a,		    0,		4},
    /* 3D */	{"DEC A",		"dec reg a", 	            op_dec_reg_a,		    0,		4},
    /* 3E */	{"LD A,#",		"load imm n into reg a", 	op_ld_reg_a_imm_n,		1,		8},
    /* 3F */	{"",		"", 	NULL,		0,		0},
    /* 40 */	{"LD B,B",		"load reg b into reg b", 	op_ld_reg_b_reg_b,		0,		4},
    /* 41 */	{"LD B,C",		"load reg c into reg b", 	op_ld_reg_b_reg_c,		0,		4},
    /* 42 */	{"LD B,D",		"load reg d into reg b", 	op_ld_reg_b_reg_d,		0,		4},
    /* 43 */	{"LD B,E",		"load reg e into reg b", 	op_ld_reg_b_reg_e,		0,		4},
    /* 44 */	{"LD B,H",		"load reg h into reg b", 	op_ld_reg_b_reg_h,		0,		4},
    /* 45 */	{"LD B,L",		"load reg l into reg b", 	op_ld_reg_b_reg_l,		0,		4},
    /* 46 */	{"LD B,(HL)",	"load ind hl into reg b", 	op_ld_reg_b_ind_hl,		0,		8},
    /* 47 */	{"LD B,A",		"load reg a into reg b", 	op_ld_reg_b_reg_a,		0,		4},
    /* 48 */	{"LD C,B",		"load reg b into reg c", 	op_ld_reg_c_reg_b,		0,		4},
    /* 49 */	{"LD C,C",		"load reg c into reg c", 	op_ld_reg_c_reg_c,		0,		4},
    /* 4A */	{"LD C,D",		"load reg d into reg c", 	op_ld_reg_c_reg_d,		0,		4},
    /* 4B */	{"LD C,E",		"load reg e into reg c", 	op_ld_reg_c_reg_e,		0,		4},
    /* 4C */	{"LD C,H",		"load reg h into reg c", 	op_ld_reg_c_reg_h,		0,		4},
    /* 4D */	{"LD C,L",		"load reg l into reg c", 	op_ld_reg_c_reg_l,		0,		4},
    /* 4E */	{"LD C,(HL)",	"load ind hl into reg c", 	op_ld_reg_c_ind_hl,		0,		8},
    /* 4F */	{"LD C,A",		"load reg a into reg c", 	op_ld_reg_c_reg_a,		0,		4},
    /* 50 */	{"LD D,B",		"load reg b into reg d", 	op_ld_reg_d_reg_b,		0,		4},
    /* 51 */	{"LD D,C",		"load reg c into reg d", 	op_ld_reg_d_reg_c,		0,		4},
    /* 52 */	{"LD D,D",		"load reg d into reg d", 	op_ld_reg_d_reg_d,		0,		4},
    /* 53 */	{"LD D,E",		"load reg e into reg d", 	op_ld_reg_d_reg_e,		0,		4},
    /* 54 */	{"LD D,H",		"load reg h into reg d", 	op_ld_reg_d_reg_h,		0,		4},
    /* 55 */	{"LD D,L",		"load reg l into reg d", 	op_ld_reg_d_reg_l,		0,		4},
    /* 56 */	{"LD D,(HL)",	"load ind hl into reg d", 	op_ld_reg_d_ind_hl,		0,		8},
    /* 57 */	{"LD D,A",		"load reg a into reg d", 	op_ld_reg_d_reg_a,		0,		4},
    /* 58 */	{"LD E,B",		"load reg b into reg e", 	op_ld_reg_e_reg_b,		0,		4},
    /* 59 */	{"LD E,C",		"load reg c into reg e", 	op_ld_reg_e_reg_c,		0,		4},
    /* 5A */	{"LD E,D",		"load reg d into reg e", 	op_ld_reg_e_reg_d,		0,		4},
    /* 5B */	{"LD E,E",		"load reg e into reg e", 	op_ld_reg_e_reg_e,		0,		4},
    /* 5C */	{"LD E,H",		"load reg h into reg e", 	op_ld_reg_e_reg_h,		0,		4},
    /* 5D */	{"LD E,L",		"load reg l into reg e", 	op_ld_reg_e_reg_l,		0,		4},
    /* 5E */	{"LD E,(HL)",	"load ind hl into reg e", 	op_ld_reg_e_ind_hl,		0,		8},
    /* 5F */	{"LD E,A",		"load reg a into reg e", 	op_ld_reg_e_reg_a,		0,		4},
    /* 60 */	{"LD H,B",		"load reg b into reg h", 	op_ld_reg_h_reg_b,		0,		4},
    /* 61 */	{"LD H,C",		"load reg c into reg h", 	op_ld_reg_h_reg_c,		0,		4},
    /* 62 */	{"LD H,D",		"load reg d into reg h", 	op_ld_reg_h_reg_d,		0,		4},
    /* 63 */	{"LD H,E",		"load reg e into reg h", 	op_ld_reg_h_reg_e,		0,		4},
    /* 64 */	{"LD H,H",		"load reg h into reg h", 	op_ld_reg_h_reg_h,		0,		4},
    /* 65 */	{"LD H,L",		"load reg l into reg h", 	op_ld_reg_h_reg_l,		0,		4},
    /* 66 */	{"LD H,(HL)",	"load ind hl into reg h", 	op_ld_reg_h_ind_hl,		0,		8},
    /* 67 */	{"LD H,A",		"load reg a into reg h", 	op_ld_reg_h_reg_a,		0,		4},
    /* 68 */	{"LD L,B",		"load reg b into reg l", 	op_ld_reg_l_reg_b,		0,		4},
    /* 69 */	{"LD L,C",		"load reg c into reg l", 	op_ld_reg_l_reg_c,		0,		4},
    /* 6A */	{"LD L,D",		"load reg d into reg l", 	op_ld_reg_l_reg_d,		0,		4},
    /* 6B */	{"LD L,E",		"load reg e into reg l", 	op_ld_reg_l_reg_e,		0,		4},
    /* 6C */	{"LD L,H",		"load reg h into reg l", 	op_ld_reg_l_reg_h,		0,		4},
    /* 6D */	{"LD L,L",		"load reg l into reg l", 	op_ld_reg_l_reg_l,		0,		4},
    /* 6E */	{"LD L,(HL)",	"load ind hl into reg l", 	op_ld_reg_l_ind_hl,		0,		8},
    /* 6F */	{"LD L,A",		"load reg a into reg l", 	op_ld_reg_l_reg_a,		0,		4},
    /* 70 */	{"LD (HL),B",	"load reg b into ind hl", 	op_ld_ind_hl_reg_b,		0,		8},
    /* 71 */	{"LD (HL),C",	"load reg c into ind hl", 	op_ld_ind_hl_reg_c,		0,		8},
    /* 72 */	{"LD (HL),D",	"load reg d into ind hl", 	op_ld_ind_hl_reg_d,		0,		8},
    /* 73 */	{"LD (HL),E",	"load reg e into ind hl", 	op_ld_ind_hl_reg_e,		0,		8},
    /* 74 */	{"LD (HL),H",	"load reg h into ind hl", 	op_ld_ind_hl_reg_h,		0,		8},
    /* 75 */	{"LD (HL),L",	"load reg l into ind hl", 	op_ld_ind_hl_reg_l,		0,		8},
    /* 76 */	{"",		"", 	NULL,		0,		0},
    /* 77 */	{"LD (HL),A",	"load reg a into ind hl", 	op_ld_ind_hl_reg_a,		0,		8},
    /* 78 */	{"LD A,B",		"load reg b into reg a", 	op_ld_reg_a_reg_b,		0,		4},
    /* 79 */	{"LD A,C",		"load reg c into reg a", 	op_ld_reg_a_reg_c,		0,		4},
    /* 7A */	{"LD A,D",		"load reg d into reg a", 	op_ld_reg_a_reg_d,		0,		4},
    /* 7B */	{"LD A,E",		"load reg e into reg a", 	op_ld_reg_a_reg_e,		0,		4},
    /* 7C */	{"LD A,H",		"load reg h into reg a", 	op_ld_reg_a_reg_h,		0,		4},
    /* 7D */	{"LD A,L",		"load reg l into reg a", 	op_ld_reg_a_reg_l,		0,		4},
    /* 7E */	{"LD A,(HL)",	"load ind hl into reg a", 	op_ld_reg_a_ind_hl,		0,		8},
    /* 7F */	{"LD A,A",		"load reg a into reg a", 	op_ld_reg_a_reg_a,		0,		4},
    /* 80 */	{"ADD A,B",		"add reg b to reg a", 	    op_add_reg_a_reg_b,		0,		4},
    /* 81 */	{"ADD A,C",		"add reg c to reg a", 	    op_add_reg_a_reg_c,		0,		4},
    /* 82 */	{"ADD A,D",		"add reg d to reg a", 	    op_add_reg_a_reg_d,		0,		4},
    /* 83 */	{"ADD A,E",		"add reg e to reg a", 	    op_add_reg_a_reg_e,		0,		4},
    /* 84 */	{"ADD A,H",		"add reg h to reg a", 	    op_add_reg_a_reg_h,		0,		4},
    /* 85 */	{"ADD A,L",		"add reg l to reg a", 	    op_add_reg_a_reg_l,		0,		4},
    /* 86 */	{"ADD A,(HL)",	"add ind hl to reg a", 	    op_add_reg_a_ind_hl,	0,		8},
    /* 87 */	{"ADD A,A",		"add reg a to reg a", 	    op_add_reg_a_reg_a,		0,		4},
    /* 88 */	{"ADC A,B",		"add+c reg b to reg a", 	op_adc_reg_a_reg_b,		0,		4},
    /* 89 */	{"ADC A,C",		"add+c reg c to reg a", 	op_adc_reg_a_reg_c,		0,		4},
    /* 8A */	{"ADC A,D",		"add+c reg d to reg a", 	op_adc_reg_a_reg_d,		0,		4},
    /* 8B */	{"ADC A,E",		"add+c reg e to reg a", 	op_adc_reg_a_reg_e,		0,		4},
    /* 8C */	{"ADC A,H",		"add+c reg h to reg a", 	op_adc_reg_a_reg_h,		0,		4},
    /* 8D */	{"ADC A,L",		"add+c reg l to reg a", 	op_adc_reg_a_reg_l,		0,		4},
    /* 8E */	{"ADC A,(HL)",	"add+c imm hl to reg a", 	op_adc_reg_a_ind_hl,	0,		8},
    /* 8F */	{"ADC A,A",		"add+c reg a to reg a", 	op_adc_reg_a_reg_a,		0,		4},
    /* 90 */	{"SUB B",		"sub reg b from reg a", 	op_sub_reg_b,		    0,		4},
    /* 91 */	{"SUB C",		"sub reg c from reg a", 	op_sub_reg_c,		    0,		4},
    /* 92 */	{"SUB D",		"sub reg d from reg a", 	op_sub_reg_d,		    0,		4},
    /* 93 */	{"SUB E",		"sub reg e from reg a", 	op_sub_reg_e,		    0,		4},
    /* 94 */	{"SUB H",		"sub reg h from reg a", 	op_sub_reg_h,		    0,		4},
    /* 95 */	{"SUB L",		"sub reg l from reg a", 	op_sub_reg_l,		    0,		4},
    /* 96 */	{"SUB (HL)",	"sub ind hl from reg a", 	op_sub_ind_hl,		    0,		8},
    /* 97 */	{"SUB A",		"sub reg a from reg a", 	op_sub_reg_a,		    0,		4},
    /* 98 */	{"SBC B",		"sub+c reg b from reg a", 	op_sbc_reg_a_reg_b,		0,		4},
    /* 99 */	{"SBC C",		"sub+c reg c from reg a", 	op_sbc_reg_a_reg_c,		0,		4},
    /* 9A */	{"SBC D",		"sub+c reg d from reg a", 	op_sbc_reg_a_reg_d,		0,		4},
    /* 9B */	{"SBC E",		"sub+c reg e from reg a", 	op_sbc_reg_a_reg_e,		0,		4},
    /* 9C */	{"SBC H",		"sub+c reg h from reg a", 	op_sbc_reg_a_reg_h,		0,		4},
    /* 9D */	{"SBC L",		"sub+c reg l from reg a", 	op_sbc_reg_a_reg_l,		0,		4},
    /* 9E */	{"SBC (HL)",	"sub+c ind hl from reg a", 	op_sbc_reg_a_ind_hl,	0,		8},
    /* 9F */	{"SBC A",		"sub+c reg a from reg a", 	op_sbc_reg_a_reg_a,		0,		4},
    /* A0 */	{"AND B",		"and reg b with reg a", 	op_and_reg_b,		    0,		4},
    /* A1 */	{"AND C",		"and reg c with reg a", 	op_and_reg_c,		    0,		4},
    /* A2 */	{"AND D",		"and reg d with reg a", 	op_and_reg_d,		    0,		4},
    /* A3 */	{"AND E",		"and reg e with reg a", 	op_and_reg_e,		    0,		4},
    /* A4 */	{"AND H",		"and reg h with reg a", 	op_and_reg_h,		    0,		4},
    /* A5 */	{"AND L",		"and reg l with reg a", 	op_and_reg_l,		    0,		4},
    /* A6 */	{"AND (HL)",	"and ind hl with reg a", 	op_and_ind_hl,		    0,		8},
    /* A7 */	{"AND A",		"and reg a with reg a", 	op_and_reg_a,		    0,		4},
    /* A8 */	{"XOR B",		"xor reg b with reg a", 	op_xor_reg_b,		    0,		4},
    /* A9 */	{"XOR C",		"xor reg c with reg a", 	op_xor_reg_c,		    0,		4},
    /* AA */	{"XOR D",		"xor reg d with reg a", 	op_xor_reg_d,		    0,		4},
    /* AB */	{"XOR E",		"xor reg e with reg a", 	op_xor_reg_e,		    0,		4},
    /* AC */	{"XOR H",		"xor reg h with reg a", 	op_xor_reg_h,		    0,		4},
    /* AD */	{"XOR L",		"xor reg l with reg a", 	op_xor_reg_l,		    0,		4},
    /* AE */	{"XOR (HL)",	"xor ind hl with reg a", 	op_xor_ind_hl,		    0,		8},
    /* AF */	{"XOR A",		"xor reg a with reg a", 	op_xor_reg_a,		    0,		4},
    /* B0 */	{"OR B",		"or reg b with reg a", 	    op_or_reg_b,		    0,		4},
    /* B1 */	{"OR C",		"or reg c with reg a", 	    op_or_reg_c,		    0,		4},
    /* B2 */	{"OR D",		"or reg d with reg a", 	    op_or_reg_d,		    0,		4},
    /* B3 */	{"OR E",		"or reg e with reg a", 	    op_or_reg_e,		    0,		4},
    /* B4 */	{"OR H",		"or reg h with reg a", 	    op_or_reg_h,		    0,		4},
    /* B5 */	{"OR L",		"or reg l with reg a", 	    op_or_reg_l,		    0,		4},
    /* B6 */	{"OR (HL)",		"or ind hl with reg a", 	op_or_ind_hl,		    0,		8},
    /* B7 */	{"OR A",		"or reg a with reg a", 	    op_or_reg_a,		    0,		4},
    /* B8 */	{"CP B",		"cmp reg b with reg a", 	op_cp_reg_b,		    0,		4},
    /* B9 */	{"CP C",		"cmp reg c with reg a", 	op_cp_reg_c,		    0,		4},
    /* BA */	{"CP D",		"cmp reg d with reg a", 	op_cp_reg_d,		    0,		4},
    /* BB */	{"CP E",		"cmp reg e with reg a", 	op_cp_reg_e,		    0,		4},
    /* BC */	{"CP H",		"cmp reg h with reg a", 	op_cp_reg_h,		    0,		4},
    /* BD */	{"CP L",		"cmp reg l with reg a", 	op_cp_reg_l,		    0,		4},
    /* BE */	{"CP (HL)",		"cmp ind hl with reg a", 	op_cp_ind_hl,		    0,		8},
    /* BF */	{"CP A",		"cmp reg a with reg a", 	op_cp_reg_a,		    0,		4},
    /* C0 */	{"",		"", 	NULL,		0,		0},
    /* C1 */	{"POP BC",		"pop stack into reg bc", 	op_pop_reg_bc,		    0,		12},
    /* C2 */	{"",		"", 	NULL,		0,		0},
    /* C3 */	{"",		"", 	NULL,		0,		0},
    /* C4 */	{"",		"", 	NULL,		0,		0},
    /* C5 */	{"PUSH BC",		"push reg bc onto stack", 	op_push_reg_bc,		    0,		16},
    /* C6 */	{"ADD A,#",		"add imm n to reg a", 	    op_add_reg_a_imm_n,		1,		8},
    /* C7 */	{"",		"", 	NULL,		0,		0},
    /* C8 */	{"",		"", 	NULL,		0,		0},
    /* C9 */	{"",		"", 	NULL,		0,		0},
    /* CA */	{"",		"", 	NULL,		0,		0},
    /* CB */	{"CB",		    "extended inst", 	        op_cb,		            0,		0},
    /* CC */	{"",		"", 	NULL,		0,		0},
    /* CD */	{"",		"", 	NULL,		0,		0},
    /* CE */	{"ADC A,#",		"add+c imm n to reg a", 	op_adc_reg_a_imm_n,		1,		8},
    /* CF */	{"",		"", 	NULL,		0,		0},
    /* D0 */	{"",		"", 	NULL,		0,		0},
    /* D1 */	{"POP DE",		"pop stack into reg de", 	op_pop_reg_de,		    0,		12},
    /* D2 */	{"",		"", 	NULL,		0,		0},
    /* D3 */	{"",		"", 	NULL,		0,		0},
    /* D4 */	{"",		"", 	NULL,		0,		0},
    /* D5 */	{"PUSH DE",		"push reg de onto stack", 	op_push_reg_de,		    0,		16},
    /* D6 */	{"SUB #",		"sub imm n from reg a", 	op_sub_imm_n,		    1,		8},
    /* D7 */	{"",		"", 	NULL,		0,		0},
    /* D8 */	{"",		"", 	NULL,		0,		0},
    /* D9 */	{"",		"", 	NULL,		0,		0},
    /* DA */	{"",		"", 	NULL,		0,		0},
    /* DB */	{"",		"", 	NULL,		0,		0},
    /* DC */	{"",		"", 	NULL,		0,		0},
    /* DD */	{"",		"", 	NULL,		0,		0},
    /* DE */	{"",		"", 	NULL,		0,		0},
    /* DF */	{"",		"", 	NULL,		0,		0},
    /* E0 */	{"LDH (n),A",	"ld reg a into $ff00+n", 	op_ldh_off_n_reg_a,		1,		12},
    /* E1 */	{"POP HL",		"pop stack into reg hl", 	op_pop_reg_hl,		    0,		12},
    /* E2 */	{"LD (C),A",	"load reg a into $ff00+c", 	op_ld_off_c_reg_a,		0,		8},
    /* E3 */	{"",		"", 	NULL,		0,		0},
    /* E4 */	{"",		"", 	NULL,		0,		0},
    /* E5 */	{"PUSH HL",		"push reg hl onto stack", 	op_push_reg_hl,		    0,		16},
    /* E6 */	{"AND #",		"and imm n with reg a", 	op_and_imm_n,		    1,		8},
    /* E7 */	{"",		"", 	NULL,		0,		0},
    /* E8 */	{"ADD SP,#",	"add imm n to reg sp", 	    op_add_reg_sp_imm_n,	0,		16},
    /* E9 */	{"",		"", 	NULL,		0,		0},
    /* EA */	{"LD (nn),A",	"load reg a into ind nn", 	op_ld_ind_nn_reg_a,		2,		16},
    /* EB */	{"",		"", 	NULL,		0,		0},
    /* EC */	{"",		"", 	NULL,		0,		0},
    /* ED */	{"",		"", 	NULL,		0,		0},
    /* EE */	{"XOR #",		"xor imm n with reg a", 	op_xor_imm_n,		    1,		8},
    /* EF */	{"",		"", 	NULL,		0,		0},
    /* F0 */	{"LDH A,(n)",	"load off n into reg a", 	op_ldh_reg_a_off_n,		1,		12},
    /* F1 */	{"POP AF",		"pop stack into reg af", 	op_pop_reg_af,		    0,		12},
    /* F2 */	{"LD A,(C)",	"load $ff00+c into reg a", 	op_ld_reg_a_off_c,		0,		8},
    /* F3 */	{"",		"", 	NULL,		0,		0},
    /* F4 */	{"",		"", 	NULL,		0,		0},
    /* F5 */	{"PUSH AF",		"push reg af onto stack", 	op_push_reg_af,		    0,		16},
    /* F6 */	{"OR #",		"or imm n with reg a", 	    op_or_imm_n,		    1,		8},
    /* F7 */	{"",		"", 	NULL,		0,		0},
    /* F8 */	{"LDHL SP,n",	"lea sp+n into hl", 	    op_ldhl_sp_off_n,		1,		12},
    /* F9 */	{"LD SP,HL",	"load hl into sp", 	        op_ld_sp_reg_hl,		0,		8},
    /* FA */	{"LD A,(nn)",	"load ind nn into reg a", 	op_ld_reg_a_ind_nn,		2,		16},
    /* FB */	{"",		"", 	NULL,		0,		0},
    /* FC */	{"",		"", 	NULL,		0,		0},
    /* FD */	{"",		"", 	NULL,		0,		0},
    /* FE */	{"CP #",		"cmp imm n with reg a", 	op_cp_imm_n,		    1,		8},
    /* FF */	{"",		"", 	NULL,		0,		0},


};

cpuinst cbinst[] = {
    /* 00 */    {"",            "",     NULL,           0},
    /* 01 */    {"",            "",     NULL,           0},
    /* 02 */    {"",            "",     NULL,           0},
    /* 03 */    {"",            "",     NULL,           0},
    /* 04 */    {"",            "",     NULL,           0},
    /* 05 */    {"",            "",     NULL,           0},
    /* 06 */    {"",            "",     NULL,           0},
    /* 07 */    {"",            "",     NULL,           0},
    /* 08 */    {"",            "",     NULL,           0},
    /* 09 */    {"",            "",     NULL,           0},
    /* 0A */    {"",            "",     NULL,           0},
    /* 0B */    {"",            "",     NULL,           0},
    /* 0C */    {"",            "",     NULL,           0},
    /* 0D */    {"",            "",     NULL,           0},
    /* 0E */    {"",            "",     NULL,           0},
    /* 0F */    {"",            "",     NULL,           0},
    /* 10 */    {"",            "",     NULL,           0},
    /* 11 */    {"",            "",     NULL,           0},
    /* 12 */    {"",            "",     NULL,           0},
    /* 13 */    {"",            "",     NULL,           0},
    /* 14 */    {"",            "",     NULL,           0},
    /* 15 */    {"",            "",     NULL,           0},
    /* 16 */    {"",            "",     NULL,           0},
    /* 17 */    {"",            "",     NULL,           0},
    /* 18 */    {"",            "",     NULL,           0},
    /* 19 */    {"",            "",     NULL,           0},
    /* 1A */    {"",            "",     NULL,           0},
    /* 1B */    {"",            "",     NULL,           0},
    /* 1C */    {"",            "",     NULL,           0},
    /* 1D */    {"",            "",     NULL,           0},
    /* 1E */    {"",            "",     NULL,           0},
    /* 1F */    {"",            "",     NULL,           0},
    /* 20 */    {"",            "",     NULL,           0},
    /* 21 */    {"",            "",     NULL,           0},
    /* 22 */    {"",            "",     NULL,           0},
    /* 23 */    {"",            "",     NULL,           0},
    /* 24 */    {"",            "",     NULL,           0},
    /* 25 */    {"",            "",     NULL,           0},
    /* 26 */    {"",            "",     NULL,           0},
    /* 27 */    {"",            "",     NULL,           0},
    /* 28 */    {"",            "",     NULL,           0},
    /* 29 */    {"",            "",     NULL,           0},
    /* 2A */    {"",            "",     NULL,           0},
    /* 2B */    {"",            "",     NULL,           0},
    /* 2C */    {"",            "",     NULL,           0},
    /* 2D */    {"",            "",     NULL,           0},
    /* 2E */    {"",            "",     NULL,           0},
    /* 2F */    {"",            "",     NULL,           0},
    /* 30 */    {"",            "",     NULL,           0},
    /* 31 */    {"",            "",     NULL,           0},
    /* 32 */    {"",            "",     NULL,           0},
    /* 33 */    {"",            "",     NULL,           0},
    /* 34 */    {"",            "",     NULL,           0},
    /* 35 */    {"",            "",     NULL,           0},
    /* 36 */    {"",            "",     NULL,           0},
    /* 37 */    {"",            "",     NULL,           0},
    /* 38 */    {"",            "",     NULL,           0},
    /* 39 */    {"",            "",     NULL,           0},
    /* 3A */    {"",            "",     NULL,           0},
    /* 3B */    {"",            "",     NULL,           0},
    /* 3C */    {"",            "",     NULL,           0},
    /* 3D */    {"",            "",     NULL,           0},
    /* 3E */    {"",            "",     NULL,           0},
    /* 3F */    {"",            "",     NULL,           0},
    /* 40 */    {"",            "",     NULL,           0},
    /* 41 */    {"",            "",     NULL,           0},
    /* 42 */    {"",            "",     NULL,           0},
    /* 43 */    {"",            "",     NULL,           0},
    /* 44 */    {"",            "",     NULL,           0},
    /* 45 */    {"",            "",     NULL,           0},
    /* 46 */    {"",            "",     NULL,           0},
    /* 47 */    {"",            "",     NULL,           0},
    /* 48 */    {"",            "",     NULL,           0},
    /* 49 */    {"",            "",     NULL,           0},
    /* 4A */    {"",            "",     NULL,           0},
    /* 4B */    {"",            "",     NULL,           0},
    /* 4C */    {"",            "",     NULL,           0},
    /* 4D */    {"",            "",     NULL,           0},
    /* 4E */    {"",            "",     NULL,           0},
    /* 4F */    {"",            "",     NULL,           0},
    /* 50 */    {"",            "",     NULL,           0},
    /* 51 */    {"",            "",     NULL,           0},
    /* 52 */    {"",            "",     NULL,           0},
    /* 53 */    {"",            "",     NULL,           0},
    /* 54 */    {"",            "",     NULL,           0},
    /* 55 */    {"",            "",     NULL,           0},
    /* 56 */    {"",            "",     NULL,           0},
    /* 57 */    {"",            "",     NULL,           0},
    /* 58 */    {"",            "",     NULL,           0},
    /* 59 */    {"",            "",     NULL,           0},
    /* 5A */    {"",            "",     NULL,           0},
    /* 5B */    {"",            "",     NULL,           0},
    /* 5C */    {"",            "",     NULL,           0},
    /* 5D */    {"",            "",     NULL,           0},
    /* 5E */    {"",            "",     NULL,           0},
    /* 5F */    {"",            "",     NULL,           0},
    /* 60 */    {"",            "",     NULL,           0},
    /* 61 */    {"",            "",     NULL,           0},
    /* 62 */    {"",            "",     NULL,           0},
    /* 63 */    {"",            "",     NULL,           0},
    /* 64 */    {"",            "",     NULL,           0},
    /* 65 */    {"",            "",     NULL,           0},
    /* 66 */    {"",            "",     NULL,           0},
    /* 67 */    {"",            "",     NULL,           0},
    /* 68 */    {"",            "",     NULL,           0},
    /* 69 */    {"",            "",     NULL,           0},
    /* 6A */    {"",            "",     NULL,           0},
    /* 6B */    {"",            "",     NULL,           0},
    /* 6C */    {"",            "",     NULL,           0},
    /* 6D */    {"",            "",     NULL,           0},
    /* 6E */    {"",            "",     NULL,           0},
    /* 6F */    {"",            "",     NULL,           0},
    /* 70 */    {"",            "",     NULL,           0},
    /* 71 */    {"",            "",     NULL,           0},
    /* 72 */    {"",            "",     NULL,           0},
    /* 73 */    {"",            "",     NULL,           0},
    /* 74 */    {"",            "",     NULL,           0},
    /* 75 */    {"",            "",     NULL,           0},
    /* 76 */    {"",            "",     NULL,           0},
    /* 77 */    {"",            "",     NULL,           0},
    /* 78 */    {"",            "",     NULL,           0},
    /* 79 */    {"",            "",     NULL,           0},
    /* 7A */    {"",            "",     NULL,           0},
    /* 7B */    {"",            "",     NULL,           0},
    /* 7C */    {"",            "",     NULL,           0},
    /* 7D */    {"",            "",     NULL,           0},
    /* 7E */    {"",            "",     NULL,           0},
    /* 7F */    {"",            "",     NULL,           0},
    /* 80 */    {"",            "",     NULL,           0},
    /* 81 */    {"",            "",     NULL,           0},
    /* 82 */    {"",            "",     NULL,           0},
    /* 83 */    {"",            "",     NULL,           0},
    /* 84 */    {"",            "",     NULL,           0},
    /* 85 */    {"",            "",     NULL,           0},
    /* 86 */    {"",            "",     NULL,           0},
    /* 87 */    {"",            "",     NULL,           0},
    /* 88 */    {"",            "",     NULL,           0},
    /* 89 */    {"",            "",     NULL,           0},
    /* 8A */    {"",            "",     NULL,           0},
    /* 8B */    {"",            "",     NULL,           0},
    /* 8C */    {"",            "",     NULL,           0},
    /* 8D */    {"",            "",     NULL,           0},
    /* 8E */    {"",            "",     NULL,           0},
    /* 8F */    {"",            "",     NULL,           0},
    /* 90 */    {"",            "",     NULL,           0},
    /* 91 */    {"",            "",     NULL,           0},
    /* 92 */    {"",            "",     NULL,           0},
    /* 93 */    {"",            "",     NULL,           0},
    /* 94 */    {"",            "",     NULL,           0},
    /* 95 */    {"",            "",     NULL,           0},
    /* 96 */    {"",            "",     NULL,           0},
    /* 97 */    {"",            "",     NULL,           0},
    /* 98 */    {"",            "",     NULL,           0},
    /* 99 */    {"",            "",     NULL,           0},
    /* 9A */    {"",            "",     NULL,           0},
    /* 9B */    {"",            "",     NULL,           0},
    /* 9C */    {"",            "",     NULL,           0},
    /* 9D */    {"",            "",     NULL,           0},
    /* 9E */    {"",            "",     NULL,           0},
    /* 9F */    {"",            "",     NULL,           0},
    /* A0 */    {"",            "",     NULL,           0},
    /* A1 */    {"",            "",     NULL,           0},
    /* A2 */    {"",            "",     NULL,           0},
    /* A3 */    {"",            "",     NULL,           0},
    /* A4 */    {"",            "",     NULL,           0},
    /* A5 */    {"",            "",     NULL,           0},
    /* A6 */    {"",            "",     NULL,           0},
    /* A7 */    {"",            "",     NULL,           0},
    /* A8 */    {"",            "",     NULL,           0},
    /* A9 */    {"",            "",     NULL,           0},
    /* AA */    {"",            "",     NULL,           0},
    /* AB */    {"",            "",     NULL,           0},
    /* AC */    {"",            "",     NULL,           0},
    /* AD */    {"",            "",     NULL,           0},
    /* AE */    {"",            "",     NULL,           0},
    /* AF */    {"",            "",     NULL,           0},
    /* B0 */    {"",            "",     NULL,           0},
    /* B1 */    {"",            "",     NULL,           0},
    /* B2 */    {"",            "",     NULL,           0},
    /* B3 */    {"",            "",     NULL,           0},
    /* B4 */    {"",            "",     NULL,           0},
    /* B5 */    {"",            "",     NULL,           0},
    /* B6 */    {"",            "",     NULL,           0},
    /* B7 */    {"",            "",     NULL,           0},
    /* B8 */    {"",            "",     NULL,           0},
    /* B9 */    {"",            "",     NULL,           0},
    /* BA */    {"",            "",     NULL,           0},
    /* BB */    {"",            "",     NULL,           0},
    /* BC */    {"",            "",     NULL,           0},
    /* BD */    {"",            "",     NULL,           0},
    /* BE */    {"",            "",     NULL,           0},
    /* BF */    {"",            "",     NULL,           0},
    /* C0 */    {"",            "",     NULL,           0},
    /* C1 */    {"",            "",     NULL,           0},
    /* C2 */    {"",            "",     NULL,           0},
    /* C3 */    {"",            "",     NULL,           0},
    /* C4 */    {"",            "",     NULL,           0},
    /* C5 */    {"",            "",     NULL,           0},
    /* C6 */    {"",            "",     NULL,           0},
    /* C7 */    {"",            "",     NULL,           0},
    /* C8 */    {"",            "",     NULL,           0},
    /* C9 */    {"",            "",     NULL,           0},
    /* CA */    {"",            "",     NULL,           0},
    /* CB */    {"",            "",     NULL,           0},
    /* CC */    {"",            "",     NULL,           0},
    /* CD */    {"",            "",     NULL,           0},
    /* CE */    {"",            "",     NULL,           0},
    /* CF */    {"",            "",     NULL,           0},
    /* D0 */    {"",            "",     NULL,           0},
    /* D1 */    {"",            "",     NULL,           0},
    /* D2 */    {"",            "",     NULL,           0},
    /* D3 */    {"",            "",     NULL,           0},
    /* D4 */    {"",            "",     NULL,           0},
    /* D5 */    {"",            "",     NULL,           0},
    /* D6 */    {"",            "",     NULL,           0},
    /* D7 */    {"",            "",     NULL,           0},
    /* D8 */    {"",            "",     NULL,           0},
    /* D9 */    {"",            "",     NULL,           0},
    /* DA */    {"",            "",     NULL,           0},
    /* DB */    {"",            "",     NULL,           0},
    /* DC */    {"",            "",     NULL,           0},
    /* DD */    {"",            "",     NULL,           0},
    /* DE */    {"",            "",     NULL,           0},
    /* DF */    {"",            "",     NULL,           0},
    /* E0 */    {"",            "",     NULL,           0},
    /* E1 */    {"",            "",     NULL,           0},
    /* E2 */    {"",            "",     NULL,           0},
    /* E3 */    {"",            "",     NULL,           0},
    /* E4 */    {"",            "",     NULL,           0},
    /* E5 */    {"",            "",     NULL,           0},
    /* E6 */    {"",            "",     NULL,           0},
    /* E7 */    {"",            "",     NULL,           0},
    /* E8 */    {"",            "",     NULL,           0},
    /* E9 */    {"",            "",     NULL,           0},
    /* EA */    {"",            "",     NULL,           0},
    /* EB */    {"",            "",     NULL,           0},
    /* EC */    {"",            "",     NULL,           0},
    /* ED */    {"",            "",     NULL,           0},
    /* EE */    {"",            "",     NULL,           0},
    /* EF */    {"",            "",     NULL,           0},
    /* F0 */    {"",            "",     NULL,           0},
    /* F1 */    {"",            "",     NULL,           0},
    /* F2 */    {"",            "",     NULL,           0},
    /* F3 */    {"",            "",     NULL,           0},
    /* F4 */    {"",            "",     NULL,           0},
    /* F5 */    {"",            "",     NULL,           0},
    /* F6 */    {"",            "",     NULL,           0},
    /* F7 */    {"",            "",     NULL,           0},
    /* F8 */    {"",            "",     NULL,           0},
    /* F9 */    {"",            "",     NULL,           0},
    /* FA */    {"",            "",     NULL,           0},
    /* FB */    {"",            "",     NULL,           0},
    /* FC */    {"",            "",     NULL,           0},
    /* FD */    {"",            "",     NULL,           0},
    /* FE */    {"",            "",     NULL,           0},
    /* FF */    {"",            "",     NULL,           0}
};

void gb_init() {

}
void gb_reset() {
    reg.pc = 0x100;
}
void gb_load() {

}

void gb_step() {
    // TODO
    // decode inst
    // read pcbuf into opbuf
}




